apiVersion: v1
kind: Secret
metadata:
  name: prorodeo-db
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_HOST: {{ .Values.db.host }}
  DB_NAME: {{ .Values.db.name }}
  DB_USER: {{ .Values.db.user }}
  DB_PASS: {{ .Values.db.pass }}
