name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        run: |
          IMAGE=ghcr.io/${{ github.repository }}:latest
          docker build -t $IMAGE .
          docker push $IMAGE

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - name: Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
      - name: Helm upgrade
        run: |
          helm upgrade --install prorodeo charts/prorodeo-scraper \
            --namespace rodeo --create-namespace \
            --set image.repository=ghcr.io/${{ github.repository }} \
            --set image.tag=latest \
            --set db.host="${{ secrets.DB_HOST }}" \
            --set db.name="${{ secrets.DB_NAME }}" \
            --set db.user="${{ secrets.DB_USER }}" \
            --set db.pass="${{ secrets.DB_PASS }}" \
            --set s3.accessKey="${{ secrets.S3_ACCESS_KEY_ID }}" \
            --set s3.secretKey="${{ secrets.S3_SECRET_ACCESS_KEY }}" \
            --set s3.region="us-east-1" \
            --set s3.bucket="rodeo-data"
